// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorMap.EF;

#nullable disable

namespace SensorMap.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251122053812_changedSensor_PLCInputs")]
    partial class changedSensor_PLCInputs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectorID");

                    b.ToTable("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.PLC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MechId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MechId")
                        .IsUnique();

                    b.ToTable("PLCs");
                });

            modelBuilder.Entity("SensorMap.Model.PLCInputs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PLCId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PLCId");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorAssignments");
                });

            modelBuilder.Entity("SensorMap.Model.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LocationImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("XPoint")
                        .HasColumnType("REAL");

                    b.Property<double?>("YPoint")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SensorTypeID");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("SensorMap.Model.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SensorTypes");
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.HasOne("SensorMap.Model.Sector", "Sector")
                        .WithMany("Mechanisms")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SensorMap.Model.PLC", b =>
                {
                    b.HasOne("SensorMap.Model.Mechanism", "Mechanism")
                        .WithOne("PLC")
                        .HasForeignKey("SensorMap.Model.PLC", "MechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanism");
                });

            modelBuilder.Entity("SensorMap.Model.PLCInputs", b =>
                {
                    b.HasOne("SensorMap.Model.PLC", "PLC")
                        .WithMany("Inputs")
                        .HasForeignKey("PLCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SensorMap.Model.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PLC");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.HasOne("SensorMap.Model.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.Navigation("PLC");
                });

            modelBuilder.Entity("SensorMap.Model.PLC", b =>
                {
                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("SensorMap.Model.Sector", b =>
                {
                    b.Navigation("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
