// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorMap.EF;

#nullable disable

namespace SensorMap.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251209181026_addedManufForPLC")]
    partial class addedManufForPLC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PLCID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PLCID");

                    b.HasIndex("SectorID");

                    b.ToTable("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.PLC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PLCManufId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PLCManufId");

                    b.ToTable("PLCs");
                });

            modelBuilder.Entity("SensorMap.Model.PLCManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PLC_Manufacturers");
                });

            modelBuilder.Entity("SensorMap.Model.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SensorTypeID");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("SensorMap.Model.SensorAssignments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LocationImage")
                        .HasColumnType("BLOB");

                    b.Property<int>("MechanismId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PLCId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MechanismId");

                    b.HasIndex("PLCId");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorAssignments");
                });

            modelBuilder.Entity("SensorMap.Model.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SensorTypes");
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.HasOne("SensorMap.Model.PLC", "PLC")
                        .WithMany("Mechanisms")
                        .HasForeignKey("PLCID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SensorMap.Model.Sector", "Sector")
                        .WithMany("Mechanisms")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLC");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SensorMap.Model.PLC", b =>
                {
                    b.HasOne("SensorMap.Model.PLCManufacturer", "PLCManufacturer")
                        .WithMany("PLCs")
                        .HasForeignKey("PLCManufId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLCManufacturer");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.HasOne("SensorMap.Model.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("SensorMap.Model.SensorAssignments", b =>
                {
                    b.HasOne("SensorMap.Model.Mechanism", "Mechanism")
                        .WithMany("Sensors")
                        .HasForeignKey("MechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SensorMap.Model.PLC", "PLC")
                        .WithMany("Inputs")
                        .HasForeignKey("PLCId");

                    b.HasOne("SensorMap.Model.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanism");

                    b.Navigation("PLC");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SensorMap.Model.PLC", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.PLCManufacturer", b =>
                {
                    b.Navigation("PLCs");
                });

            modelBuilder.Entity("SensorMap.Model.Sector", b =>
                {
                    b.Navigation("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
