// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorMap.EF;

#nullable disable

namespace SensorMap.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260709061326_addMapObject")]
    partial class addMapObject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SensorMap.Model.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<int?>("MasterDeviceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("MasterDeviceID");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SensorMap.Model.DeviceCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("DeviceCharacteristic");
                });

            modelBuilder.Entity("SensorMap.Model.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("SensorMap.Model.HelpfulFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageFile")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("MechanismId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SensorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MechanismId");

                    b.HasIndex("SensorId");

                    b.ToTable("HelpfulFiles");
                });

            modelBuilder.Entity("SensorMap.Model.MapObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<int>("MechanismId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MechanismId");

                    b.ToTable("MapObjects");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("SectorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceID");

                    b.HasIndex("SectorID");

                    b.ToTable("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SensorTypeID");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("SensorMap.Model.SensorCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SensorTypeId");

                    b.ToTable("SensorCharacteristic");
                });

            modelBuilder.Entity("SensorMap.Model.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SensorTypes");
                });

            modelBuilder.Entity("SensorMap.Model.DeviceAssignment", b =>
                {
                    b.HasBaseType("SensorMap.Model.MapObject");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceAssignments");
                });

            modelBuilder.Entity("SensorMap.Model.SensorAssignments", b =>
                {
                    b.HasBaseType("SensorMap.Model.MapObject");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorAssignments");
                });

            modelBuilder.Entity("SensorMap.Model.Device", b =>
                {
                    b.HasOne("SensorMap.Model.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId");

                    b.HasOne("SensorMap.Model.Device", "MasterDevice")
                        .WithMany("ChildrenDevices")
                        .HasForeignKey("MasterDeviceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeviceType");

                    b.Navigation("MasterDevice");
                });

            modelBuilder.Entity("SensorMap.Model.DeviceCharacteristic", b =>
                {
                    b.HasOne("SensorMap.Model.DeviceType", "DeviceType")
                        .WithMany("Characteristics")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("SensorMap.Model.HelpfulFile", b =>
                {
                    b.HasOne("SensorMap.Model.Device", "Device")
                        .WithMany("Files")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SensorMap.Model.Mechanism", "Mechanism")
                        .WithMany("Files")
                        .HasForeignKey("MechanismId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SensorMap.Model.Sensor", "Sensor")
                        .WithMany("Files")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");

                    b.Navigation("Mechanism");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorMap.Model.MapObject", b =>
                {
                    b.HasOne("SensorMap.Model.Mechanism", "Mechanism")
                        .WithMany("MapObjects")
                        .HasForeignKey("MechanismId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mechanism");
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.HasOne("SensorMap.Model.Device", "Device")
                        .WithMany("Mechanisms")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SensorMap.Model.Sector", "Sector")
                        .WithMany("Mechanisms")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.HasOne("SensorMap.Model.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("SensorMap.Model.SensorCharacteristic", b =>
                {
                    b.HasOne("SensorMap.Model.SensorType", "SensorType")
                        .WithMany("Characteristics")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("SensorMap.Model.DeviceAssignment", b =>
                {
                    b.HasOne("SensorMap.Model.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SensorMap.Model.MapObject", null)
                        .WithOne()
                        .HasForeignKey("SensorMap.Model.DeviceAssignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SensorMap.Model.SensorAssignments", b =>
                {
                    b.HasOne("SensorMap.Model.MapObject", null)
                        .WithOne()
                        .HasForeignKey("SensorMap.Model.SensorAssignments", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SensorMap.Model.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorMap.Model.Device", b =>
                {
                    b.Navigation("ChildrenDevices");

                    b.Navigation("Files");

                    b.Navigation("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.DeviceType", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SensorMap.Model.Mechanism", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("MapObjects");
                });

            modelBuilder.Entity("SensorMap.Model.Sector", b =>
                {
                    b.Navigation("Mechanisms");
                });

            modelBuilder.Entity("SensorMap.Model.Sensor", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SensorMap.Model.SensorType", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
